---
- name: Make directories
  file: state=directory dest={{ item }} owner={{ ansible_ssh_user }}
  with_items:
  - "{{ jardir }}"
  - "{{ src }}"
  - "{{ venv }}"
  - "{{ datadir }}"
  - /var/log/gallery/
  sudo: true

- name: Install Build dependencies
  apt: name={{ item }}
  with_items:
  - build-essential
  - g++
  - libzbar0
  - zbar-tools
  - libzbar-dev
  - python-pip
  sudo: true

- name: Install virtualenv
  pip: name=virtualenv
  sudo: true

- name: Fetch Python packages
  pip: name=requests virtualenv="{{ venv }}"

- name: Fetch source
  git: repo=https://github.com/andrewhead/Gallery-Paths.git dest={{ src }}
  tags:
  - code

- name: Copy default observer configuration
  copy: src=observer.conf dest=/etc/observer.conf
  sudo: true

- name: Copy wireless configuration
  copy: src=interfaces dest=/etc/network/interfaces backup=yes
  sudo: true

- name: Copy wpa_supplicant
  copy: src=wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf backup=yes
  sudo: true

- name: Compile QR reader
  command: g++ -lzbar -lpng read_qr.cpp -o read_qr
  args:
    chdir: "{{ src }}/observer"

- name: Schedule network check
  cron: name="network reboot" minute="*/10" job="{{ src }}/observer/network_reboot.sh" user="root"
  sudo: true

- name: Enable camera
  lineinfile: dest=/boot/config.txt line="start_x=1"
  sudo: true

- debug: Your Observer is ready. Reboot the board.
