---
- name: Make space
  file: state=absent dest={{ item }}
  with_items:
  - /opt/Wolfram
  sudo: true

- name: Make directories
  file: state=directory dest={{ item }} owner={{ ansible_ssh_user }}
  with_items:
  - "{{ jardir }}"
  - "{{ src }}"
  - "{{ datadir }}"
  - /var/log/gallery/
  - "{{ tmp }}"
  sudo: true

- name: Install Build dependencies
  apt: name={{ item }}
  with_items:
  - build-essential
  - g++
  - libzbar0
  - zbar-tools
  - libzbar-dev
  - python-opencv
  - libopencv-dev
  - python-pip
  - supervisor
  - python-dev
  sudo: true

- name: Install Python dependencies
  pip: name={{ item }}
  sudo: true
  with_items:
  - requests
  - picamera
  - futures

- name: Fetch source
  git: repo=https://github.com/andrewhead/Gallery-Paths.git dest={{ src }}
  tags:
  - code

- name: Get WiringPi for GPIO
  git: repo=https://github.com/WiringPi/WiringPi dest={{ tmp }}/WiringPi

- name: Build WiringPi
  command: ./build chdir={{ tmp }}/WiringPi
  sudo: true

- name: Get zbar
  git: repo=https://github.com/npinchot/zbar.git dest={{ tmp }}/zbar
  tags:
  - zbar

- name: Build zbar
  command: python setup.py install chdir={{ tmp }}/zbar
  sudo: true
  tags:
  - zbar

- name: Configure modules for GPIO and camera at same time
  copy: src=modules dest=/etc/modules
  sudo: true

- name: Copy module blacklist
  copy: src=raspi-blacklist.conf dest=/etc/modprobe.d/raspi-blacklist.conf
  sudo: true

- name: Copy default observer configuration
  template: src=observer.j2 dest=/etc/observer.conf
  sudo: true

- name: Copy wireless configuration
  copy: src=interfaces dest=/etc/network/interfaces backup=yes
  sudo: true

- name: Copy wpa_supplicant
  copy: src=wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf backup=yes
  sudo: true

- name: Enable camera
  lineinfile: dest=/boot/config.txt line="start_x=1"
  sudo: true

- name: Schedule network check
  cron: name="network reboot" minute="*/10" job="{{ src }}/observer/./network_reboot.sh" user="root"
  sudo: true

- name: Delete old cron jobs
  cron: name={{ item }} state=absent
  with_items:
  - snapshot
  - upload

- name: Configure supervisor
  template: src=supervisor.j2 dest=/etc/supervisor/conf.d/observe.conf
  sudo: true

- debug: Your Observer is ready. Reboot the board.
