---
- name: Make directories
  file: state=directory dest={{ item }} owner={{ ansible_ssh_user }}
  with_items:
  - "{{ jardir }}"
  - "{{ src }}"
  - "{{ datadir }}"
  - /var/log/gallery/
  sudo: true

- name: Install Build dependencies
  apt: name={{ item }}
  with_items:
  - build-essential
  - g++
  - libzbar0
  - zbar-tools
  - libzbar-dev
  - python-pip
  sudo: true

- name: Install Python dependencies
  pip: name=requests
  sudo: true

- name: Fetch source
  git: repo=https://github.com/andrewhead/Gallery-Paths.git dest={{ src }}
  tags:
  - code

- name: Copy default observer configuration
  copy: src=observer.conf dest=/etc/observer.conf
  sudo: true

- name: Copy wireless configuration
  copy: src=interfaces dest=/etc/network/interfaces backup=yes
  sudo: true

- name: Copy wpa_supplicant
  copy: src=wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf backup=yes
  sudo: true

- name: Compile QR reader
  command: g++ -lzbar -lpng read_qr.cpp -o read_qr
  args:
    chdir: "{{ src }}/observer"

- name: Enable camera
  lineinfile: dest=/boot/config.txt line="start_x=1"
  sudo: true

- name: Schedule network check
  cron: name="network reboot" minute="*/10" job="{{ src }}/observer/./network_reboot.sh" user="root"
  sudo: true

- name: Schedule snapshot relaunch
  cron: name="snapshot" minute="*/10" job="{{ snapjob }}"

- name: Schedule snapshot on boot
  cron: name="snapshot" special_time=reboot job="{{ snapjob }}"

- name: Schedule event upload
  cron: name="upload" minute="*/10" job="{{ src }}/observer/./upload.py {{ datadir }}/events.log 2>&1 >> /var/log/gallery/upload.log"

- debug: Your Observer is ready. Reboot the board.
